services:
  telegram-downloader-bot:
    build: .
    container_name: tg_video_downloader
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cache.db:/app/cache.db
      - ./bot_users.db:/app/bot_users.db

